In [1]:
import pandas as pd
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

In [11]:
data = pd.read_csv('dataset1.csv', delimiter=',')
data = data.drop('number', axis=1)

In [14]:
data[data['sentiment']=='netral'].to_csv('netral_only.csv')

In [17]:
df = pd.read_csv('netral_only.csv', encoding='latin1')
df = df.drop('Unnamed: 0', axis=1)
df

                                                   text sentiment
0                        haters bacot tapi masih nonton    netral
1                                         mantap kontol    netral
2                                                 setan    netral
3                                                   tai    netral
4                                                 titit    netral
...                                                 ...       ...
6978  zhar borneo muka lu kok kyknya ada dimana mana...    netral
6979      zhar zhar zhar zhar zhar zhar ini bner i like    netral
6980                     zharborneo ikut rewind gk bang    netral
6981                               zhiap bang saya juga    netral
6982                 zigi wig tombol mode batas youtube    netral

[6983 rows x 2 columns]

In [19]:
import json
with open('kata_kasar.json', 'r') as file:
    kamus = json.load(file)

def labeling(text, kamus):
    words = set(text.split())
    kata_kasar = set(kamus.keys())  
    if words & kata_kasar:
        return 'negatif'
    else:
        return 'positif'
    
df['labeling'] = df['text'].astype(str).apply(lambda x: labeling(x, kamus))
df

                                                   text sentiment labeling
0                        haters bacot tapi masih nonton    netral  negatif
1                                         mantap kontol    netral  negatif
2                                                 setan    netral  negatif
3                                                   tai    netral  negatif
4                                                 titit    netral  negatif
...                                                 ...       ...      ...
6978  zhar borneo muka lu kok kyknya ada dimana mana...    netral  positif
6979      zhar zhar zhar zhar zhar zhar ini bner i like    netral  positif
6980                     zharborneo ikut rewind gk bang    netral  positif
6981                               zhiap bang saya juga    netral  positif
6982                 zigi wig tombol mode batas youtube    netral  positif

[6983 rows x 3 columns]

In [20]:
df = df.drop('sentiment', axis=1)
df.to_csv('hasil_netral.csv', encoding='latin1')